# Generated by Django 4.2.6 on 2023-12-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pembeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=255)),
                ('NO_ANTREAN', models.ImageField(null=True, upload_to='')),
                ('PESANAN', models.CharField(max_length=255)),
            ],
        ),
    ]
