# Generated by Django 4.2.6 on 2023-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_buah', models.CharField(max_length=255)),
                ('Jumlah', models.ImageField(null=True, upload_to='')),
                ('Harga', models.CharField(max_length=255)),
            ],
        ),
    ]
